version: '3.4'

services:
  webapi:
    image: jszablanowski/autoland
    environment:
      - "ConnectionStrings__DefaultConnection=Server=autoland_db;Database=AutoLandDB;User=sa;Password=Your_password12345;MultipleActiveResultSets=true"
    ports:
      - "7000:7000"
    depends_on:
      - autoland_db
    restart: on-failure

  autoland_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password12345"
      - "ACCEPT_EULA=Y"